# Number of samples per class for training dataset
samples_number = 400

# Image size
im_size = 112

# Frames per step
frames_per_step = 16

activities_ids = {'l-arm:Shoulder external rotation and elbow flexion': 22,
                     'head:Turn left': 12,
                     'l-arm:Shoulder abduction': 24,
                     'r-arm:Shoulder extension': 35,
                     'l-leg:Hip external rotation': 27,
                     'r-arm:Shoulder internal rotation and elbow extension': 51,
                     'head:Roll left': 13,
                     'head:Turn bottom-left': 15,
                     'head:Turn right': 11,
                     'l-arm:Roll the wrist': 20,
                     'l-leg:Knee extension': 26,
                     'r-arm:Roll the wrist': 33,
                     'l-arm:Shoulder external rotation and elbow extension': 2,
                     'r-leg:Hip extension': 47,
                     'r-arm:Shoulder internal rotation': 38,
                     'r-arm:Elbow flexion': 32,
                     'r-arm:Shoulder external rotation and elbow flexion': 36,
                     'r-leg:Hip external rotation': 41,
                     'r-leg:Hip adduction': 5,
                     'l-arm:Shoulder flexion': 23,
                     'r-leg:Knee extension': 40,
                     'head:Turn top-right': 48,
                     'l-leg:Hip flexion': 29,
                     'l-leg:Hip extension': 46,
                     'head:Turn top-left': 16,
                     'l-arm:Shoulder internal rotation and elbow extension': 50,
                     'r-arm:Shoulder adduction': 30,
                     'head:Roll right': 14,
                     'l-leg:Hip adduction': 7,
                     'r-leg:Hip abduction': 8,
                     'r-arm:Shoulder external rotation and elbow extension': 4,
                     'l-arm:Shoulder internal rotation and elbow flexion': 1,
                     'l-arm:Elbow flexion': 18,
                     'head:Lean forward': 0,
                     'r-leg:Hip flexion': 43,
                     'r-leg:Knee flexion': 39,
                     'l-arm:Shoulder adduction': 17,
                     'r-arm:Shoulder external rotation': 45,
                     'r-arm:Shoulder internal rotation and elbow flexion': 3,
                     'r-arm:Shoulder abduction': 31,
                     'head:Raise the head': 9,
                     'l-arm:Elbow extension': 19,
                     'l-arm:Shoulder extension': 21,
                     'l-arm:Shoulder internal rotation': 44,
                     'l-arm:Shoulder external rotation': 49,
                     'r-arm:Elbow extension': 34,
                     'l-leg:Hip abduction': 6,
                     'l-leg:Knee flexion': 25,
                     'r-leg:Hip internal rotation': 42,
                     'head:Turn bottom-right': 10,
                     'l-leg:Hip internal rotation': 28,
                     'r-arm:Shoulder flexion': 37}

activities_tfrecords = {'head:Turn right': 0,
                        'head:Turn left': 1,
                        'head:Raise the head': 2,
                        'head:Lean forward': 3,

                        'r-arm:Shoulder extension': 4,
                        'r-arm:Shoulder adduction': 5,
                        'r-arm:Roll the wrist': 6,
                        'r-arm:Elbow flexion': 7,
                        'r-arm:Elbow extension': 8,
                        'r-arm:Shoulder flexion': 9,
                        'r-arm:Shoulder abduction': 10,

                        'l-arm:Shoulder extension': 11,
                        'l-arm:Shoulder abduction': 12,
                        'l-arm:Roll the wrist': 13,
                        'l-arm:Elbow flexion': 14,
                        'l-arm:Elbow extension': 15,
                        'l-arm:Shoulder flexion': 16,
                        'l-arm:Shoulder adduction': 17,

                        'r-leg:Hip flexion': 18,
                        'r-leg:Hip extension': 19,
                        'r-leg:Knee flexion': 20,
                        'r-leg:Knee extension': 21,

                        'l-leg:Hip flexion': 22,
                        'l-leg:Hip extension': 23,
                        'l-leg:Knee extension': 24,
                        'l-leg:Knee flexion': 25
                     }
